### ISSUE TITLE
 np.asscalar  error in execute sgdml all ethanol_dft.npz 200 1000 5000

### ISSUE THREAD

**Issue by Paulie-ai** [stefanch/sGDML#21]
Hi, Stefanch. When i try to train and validate use sgdml all , it show bugs as below: 
"
[DONE] Validation errors (MAE/RMSE): energy 0.159/0.221, forces 0.827/1.200             @ 38.5 geo/s
[CRIT] Traceback (most recent call last):
         File "/data/xxx/software/sgdml/sGDML/sgdml/cli.py", line 2216, in main
           getattr(sys.modules[__name__], args['command'])(**args)
         File "/data/xxx/software/sgdml/sGDML/sgdml/cli.py", line 617, in all
           model_dir_or_file_path = train(
         File "/data/xxx/software/sgdml/sGDML/sgdml/cli.py", line 1047, in train
           valid_errs = test(
         File "/data/xxx/software/sgdml/sGDML/sgdml/cli.py", line 1695, in test
           'mae': np.asscalar(e_mae),
         File "/home/xxx/anaconda3/envs/sgdml/lib/python3.8/site-packages/numpy/__init__.py", line 311, in __getattr__
           raise AttributeError("module {!r} has no attribute "
       AttributeError: module **'numpy' has no attribute 'asscalar'**
"
And my linux envs in conda as :
numpy                     1.23.3  
python                    3.8.0  
scipy                     1.9.1  
torch                     1.12.1   
ase                       3.22.1 

 I cannot find how to fix this error(may cli.py  has error define attribute),  can you offer some sugguestion? Thanks for your reply!

**Comment by stefanch** [comment]
This issues has been fixed in version 0.5.3. Please excuse the inconvenience.
