### ISSUE TITLE
Compilation success, fail when running.

### ISSUE THREAD

**Issue by 1a2y** [stefanch/sGDML#22]
Hi everyone,
 I have successfully installed sgdml in my (Windows 10) machine, but when I run it I have the following error message:

C:\Windows\system32>sgdml all datasets/npz/ethanol.npz 200 1000 5000
Traceback (most recent call last):
  File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.9_3.9.3312.0_x64__qbz5n2kfra8p0\lib\runpy.py", line 197, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.9_3.9.3312.0_x64__qbz5n2kfra8p0\lib\runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "C:\Users\David\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.9_qbz5n2kfra8p0\LocalCache\local-packages\Python39\Scripts\sgdml.exe\__main__.py", line 4, in <module>
  File "C:\Users\David\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.9_qbz5n2kfra8p0\LocalCache\local-packages\Python39\site-packages\sgdml\cli.py", line 67, in <module>
    from .predict import GDMLPredict
  File "C:\Users\David\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.9_qbz5n2kfra8p0\LocalCache\local-packages\Python39\site-packages\sgdml\predict.py", line 36, in <module>
    Pool = mp.get_context('fork').Pool
  File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.9_3.9.3312.0_x64__qbz5n2kfra8p0\lib\multiprocessing\context.py", line 239, in get_context
    return super().get_context(method)
  File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.9_3.9.3312.0_x64__qbz5n2kfra8p0\lib\multiprocessing\context.py", line 193, in get_context
    raise ValueError('cannot find context for %r' % method) from None
ValueError: cannot find context for 'fork'

 How can I fix it? Help is greatly appreciated ...
 Thank you very much, David.

**Comment by stefanch** [comment]
Can you please try running your command with the extra parameter "-p 1"?

**Comment by 1a2y** [comment]
Dear Stefan,
 Thanks for your reply and sorry for my delay ...
 I tried your suggestion, but it didn't work, see the screenshot.
 I am assuming that it works in Windows. Doesn't it?
 Thanks again, David.
![screenshot](https://user-images.githubusercontent.com/95612095/200033768-fdfbbb8d-c6df-4057-a79e-b2203ccbc13c.png)
